import { prisma } from "../db.js";
import { renderStageCompletionReport } from "./signedDocumentRenderer.js";
import { saveGeneratedDocument } from "./fileUpload.js";
import { sendSystemEmail, stageCompletionReportEmail } from "./systemMailer.js";
import { appBaseUrl } from "./appUrl.js";
import { REQUIRED_DOCUMENT_LABELS } from "./requiredDocuments.js";

export const STAGE_REPORT_CATEGORY = "Stage Completion Report";

// Shared by every trigger's `facts` list below -- returns null (not a
// placeholder string) for an unset date, so it's simply left out of the
// report rather than shown as a blank the way the legal-document
// templates in signedDocumentRenderer.js do.
export function fmtFactDate(value) {
  return value ? new Date(value).toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" }) : null;
}

// One fact-builder per stage, shared between the live route triggers
// (ndaRecords.js, ioiRecords.js, documents.js, visitPlans.js, dealStages.js)
// and backfillAllStageReports below -- so a report generated live and one
// generated by the backfill for the same kind of record always look
// identical, and a fact list only ever needs updating in one place.
export function ndaReportFacts(record) {
  return [
    { label: "Signed by", value: record.signerName },
    { label: "Signed on", value: fmtFactDate(record.signedAt) },
    { label: "Agreement date", value: fmtFactDate(record.agreementDate) },
    { label: "Counterparty country", value: record.counterpartyCountry },
    { label: "Owner", value: record.owner }
  ];
}

export function ioiReportFacts(record) {
  return [
    { label: "Value", value: record.value ? `${record.valueCurrency} ${Number(record.value).toLocaleString("en-US")}` : null },
    { label: "Signed on", value: fmtFactDate(record.signedAt) },
    { label: "Industry", value: record.industry },
    { label: "Geography", value: record.geography },
    { label: "Counterparty", value: record.counterparty },
    { label: "Owner", value: record.owner }
  ];
}

export function dataRoomReportFacts({ receivedCategories, totalRequired }) {
  return [
    { label: "Documents received", value: `${receivedCategories.length} of ${totalRequired}` },
    { label: "Categories", value: receivedCategories.join(", ") }
  ];
}

export function visitReportFacts(plan) {
  return [
    { label: "Location", value: plan.location },
    { label: "Region / Country", value: [plan.region, plan.country].filter(Boolean).join(", ") },
    { label: "Visit date", value: fmtFactDate(plan.plannedFor) },
    { label: "Completed on", value: fmtFactDate(plan.completedAt) },
    { label: "Cost", value: plan.costAmount ? `${plan.costCurrency} ${Number(plan.costAmount).toLocaleString("en-US")}` : null },
    { label: "Travel mode", value: plan.travelMode },
    { label: "Owner", value: plan.owner }
  ];
}

// Field Visit and Term Sheet share DealStageRecord -- same shape, branched
// by record.stage, same reasoning as clientPortalStages.js's own
// deriveDealStage for the two.
export const DEAL_STAGE_REPORT_LABEL = { FIELD_VISIT: "Field Visit", TERM_SHEET: "Term Sheet" };
export function dealStageReportFacts(record) {
  if (record.stage === "FIELD_VISIT") {
    return [
      { label: "Location", value: record.location },
      { label: "Attendees", value: record.attendees },
      { label: "Visit date", value: fmtFactDate(record.scheduledAt) },
      { label: "Completed on", value: fmtFactDate(record.completedAt) },
      { label: "Client rating", value: record.clientRating != null ? `${record.clientRating}/5` : null },
      { label: "Owner", value: record.owner }
    ];
  }
  if (record.stage === "TERM_SHEET") {
    return [
      { label: "Amount", value: record.amount },
      { label: "Valuation", value: record.valuation },
      { label: "Counterparty", value: record.counterparty },
      { label: "Issued on", value: fmtFactDate(record.scheduledAt) },
      { label: "Signed on", value: fmtFactDate(record.completedAt) },
      { label: "Owner", value: record.owner }
    ];
  }
  return null;
}

// Fires the moment any deal stage completes for a lead -- see the call
// sites in routes/ndaRecords.js, ioiRecords.js, documents.js, visitPlans.js
// and dealStages.js (field visit + term sheet). Stores a generated report
// as a real Document (so it shows up everywhere Documents already do --
// Data Room, the CRM Workspace Reports tab, the client portal) and emails
// it to the deal's owner (best-effort name match against a staff User) and
// every admin.
//
// `dedupKey` identifies the one real-world event this report is for --
// "NDA", "IOI", "DATA_ROOM", "FIELD_VISIT" and "TERM_SHEET" happen at most
// once per lead, so the key is just the stage; Visit Planning can happen
// many times per lead, so its callers pass `VISIT:<visitPlanId>` instead,
// one report per actual visit rather than one per lead.
//
// Deliberately not awaited by its callers (fire-and-forget) -- generating
// and emailing a report must never slow down or fail the actual save that
// triggered it, so every failure here is caught and logged, never thrown.
export async function generateStageReport({ leadId, dedupKey, stageLabel, facts, ownerName }) {
  try {
    const marker = `[${dedupKey}]`;
    const existing = await prisma.document.findFirst({
      where: { leadId, category: STAGE_REPORT_CATEGORY, description: { startsWith: marker } }
    });
    if (existing) return existing;

    const lead = await prisma.lead.findUnique({ where: { id: leadId }, select: { company: true, name: true } });
    if (!lead) return null;

    const generatedAt = new Date();
    const html = renderStageCompletionReport({ stageLabel, lead, facts, generatedAt });
    const doc = await saveGeneratedDocument(Buffer.from(html, "utf8"), {
      originalName: `${stageLabel} report — ${lead.company}.html`,
      mimeType: "text/html",
      category: STAGE_REPORT_CATEGORY,
      leadId,
      description: `${marker} ${stageLabel} completed for ${lead.company}.`
    });

    // Best-effort: the owner on a stage record is free text (e.g. "Rahul
    // R"), never a real relation to a User -- if nothing matches, the
    // report still generates and admins still get it, just no DOE copy.
    const recipients = new Set();
    if (ownerName) {
      const match = await prisma.user.findFirst({
        where: { name: { equals: ownerName, mode: "insensitive" } },
        select: { email: true }
      });
      if (match?.email) recipients.add(match.email.toLowerCase());
    }
    const admins = await prisma.user.findMany({ where: { role: "ADMIN" }, select: { email: true } });
    for (const admin of admins) if (admin.email) recipients.add(admin.email.toLowerCase());

    if (recipients.size) {
      const { subject, html: emailHtml, text } = stageCompletionReportEmail({
        stageLabel,
        company: lead.company,
        facts,
        reportUrl: appBaseUrl()
      });
      for (const to of recipients) {
        await sendSystemEmail({ to, subject, html: emailHtml, text }).catch(() => {});
      }
    }

    return doc;
  } catch (err) {
    console.error(`[stage-completion-report] failed for lead ${leadId} (${dedupKey}):`, err.message);
    return null;
  }
}

// One-time (but safe to re-run -- generateStageReport's own dedup guard
// makes this idempotent) sweep for stages that completed before this
// feature existed, so their history isn't just missing. Reuses the exact
// same fact-builders and generateStageReport as every live trigger, so a
// backfilled report is indistinguishable from one that fired live. Not
// wired to any automatic schedule -- triggered on demand via
// POST /api/admin/backfill-stage-reports (see routes/admin.js).
export async function backfillAllStageReports() {
  const counts = { ndaSigned: 0, ioiSigned: 0, dataRoomComplete: 0, fieldVisitCompleted: 0, termSheetCompleted: 0, visitsCompleted: 0 };

  const [ndas, iois, fieldVisits, termSheets, visits, leads] = await Promise.all([
    prisma.ndaRecord.findMany({ where: { status: "SIGNED" } }),
    prisma.ioiRecord.findMany({ where: { status: "SIGNED" } }),
    prisma.dealStageRecord.findMany({ where: { stage: "FIELD_VISIT", status: "COMPLETED" } }),
    prisma.dealStageRecord.findMany({ where: { stage: "TERM_SHEET", status: "COMPLETED" } }),
    prisma.visitPlan.findMany({ where: { status: "COMPLETED" } }),
    prisma.lead.findMany({ select: { id: true, owner: true } })
  ]);

  for (const nda of ndas) {
    await generateStageReport({ leadId: nda.leadId, dedupKey: "NDA", stageLabel: "NDA", ownerName: nda.owner, facts: ndaReportFacts(nda) });
    counts.ndaSigned++;
  }

  for (const ioi of iois) {
    await generateStageReport({ leadId: ioi.leadId, dedupKey: "IOI", stageLabel: "IOI", ownerName: ioi.owner, facts: ioiReportFacts(ioi) });
    counts.ioiSigned++;
  }

  for (const record of fieldVisits) {
    await generateStageReport({
      leadId: record.leadId,
      dedupKey: "FIELD_VISIT",
      stageLabel: DEAL_STAGE_REPORT_LABEL.FIELD_VISIT,
      ownerName: record.owner,
      facts: dealStageReportFacts(record)
    });
    counts.fieldVisitCompleted++;
  }

  for (const record of termSheets) {
    await generateStageReport({
      leadId: record.leadId,
      dedupKey: "TERM_SHEET",
      stageLabel: DEAL_STAGE_REPORT_LABEL.TERM_SHEET,
      ownerName: record.owner,
      facts: dealStageReportFacts(record)
    });
    counts.termSheetCompleted++;
  }

  for (const plan of visits) {
    await generateStageReport({
      leadId: plan.leadId,
      dedupKey: `VISIT:${plan.id}`,
      stageLabel: "Visit Planning",
      ownerName: plan.owner,
      facts: visitReportFacts(plan)
    });
    counts.visitsCompleted++;
  }

  // Data Room has no single record to scan -- recompute each lead's
  // received-vs-required checklist, same as documents.js's live trigger.
  for (const lead of leads) {
    const docs = await prisma.document.findMany({
      where: { leadId: lead.id, category: { in: REQUIRED_DOCUMENT_LABELS } },
      select: { category: true },
      distinct: ["category"]
    });
    if (docs.length >= REQUIRED_DOCUMENT_LABELS.length) {
      await generateStageReport({
        leadId: lead.id,
        dedupKey: "DATA_ROOM",
        stageLabel: "Data Room",
        ownerName: lead.owner,
        facts: dataRoomReportFacts({ receivedCategories: docs.map((d) => d.category), totalRequired: REQUIRED_DOCUMENT_LABELS.length })
      });
      counts.dataRoomComplete++;
    }
  }

  return counts;
}
